coverage:
  status:
    patch: no
    project:
      default:
        target: auto
        threshold: 1%
        branches:
          - main
        if_ci_failed: error
        informational: false
        only_pulls: false
